### PR TITLE
Update gemspec dependencies

### PR DESCRIPTION
**Pull request by flipacholas**
Related to #27 

Rake tests seem happy with Jekyll 4

### CODE REVIEW

**Comment by lucianoshl** [comment]
i tested your code and works like a charm, thanks!!

**Comment by afaundez** [comment]
Hi guys, I haven't merged this yet because I had trouble with the Bundler upgrade to 2.x, breaking a pipeline.
@flipacholas: Was it a requirement to upgrade bundler in order to update Jekyll?

**Comment by flipacholas** [comment]
@afaundez doesn't seem so, I've just reverted bundler and it still works.

**Comment by afaundez** [comment]
@flipacholas with the Gemfile.lock proposed you can't bundle with ruby < 2.3.0.
Although 2.4 is the oldest ruby version in maintenance, Jekyll 3 is declared to work with ruby >= 2.1.0.

**Comment by flipacholas** [comment]
I've corrected the lock file, looks like your Travis script is fine with it

**Pull request merged**
